[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = 'Powered by <a class="text-muted" href="https://gohugo.io/">Hugo</a> / <a class="text-muted" href="https://github.com/thuliteio/doks">Doks</a>'
    alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Doks version 1.0 just shipped!</a>'

[ja]
  languageName = "Japanese"
  contentDir = "content/ja"
  weight = 15
  [ja.params]
    languageISO = "JA"
    languageTag = "ja-JP"
    footer = 'Powered by <a class="text-muted" href="https://gohugo.io/">Hugo</a> / <a class="text-muted" href="https://github.com/thuliteio/doks">Doks</a>'
    alertText = 'Neue Version ist da! <a class="alert-link stretched-link" href="https://getdoks.org/blog/doks-v0.5/">Doks v0.5</a>'
